[package]
name = "atelier-daemon"
version = "0.1.0"
edition = "2018"

[dependencies]
atelier-core = { path = "../core" }
atelier-schema = { path = "../schema" }
atelier-importer = { path = "../importer" }
dunce = "1.0"
path-clean = "0.1"
path-slash = "0.1.1"
capnp = { version = "0.12", features = ["unaligned"] }
capnp-rpc = "0.12"
notify = "4.0.0"
lmdb = { git = "http://github.com/kabergstrom/lmdb-rs" }
rayon = "1.2"
fern = "0.5"
log = { version = "0.4", features = ["serde"] }
tokio = { version = "0.2.11", features = ["tcp", "sync", "rt-core", "rt-util", "stream"] }
futures = "0.3"
futures-tokio-compat = { git = "https://github.com/dwrensha/futures-tokio-compat", branch = "tokio-0.2" }
owning_ref = "0.4"
crossbeam-channel = "0.3"
mopa = "0.2.2"
serde = "1.0"
serde_derive = "1.0"
erased-serde = "0.3"
bincode = "1.1"
ron = "0.5"
meowhash = "0.1.2"
scoped_threadpool = "0.1.9"
num_cpus = "1.10"
smush = { version = "0.1", default-features = false, features = [ "lz4_support" ], optional = true }
chrono = "0.4.10"

[dev-dependencies]
tempfile = "3"

[features]
compression = [ "smush" ]